const PURCHASE_TICKET = 'PURCHASE_TICKET';
const GET_TICKETS = 'GET_TICKETS';
const GET_TICKETS_REQUEST = 'GET_TICKETS_REQUEST';
const SET_TICKETS_REQUEST = 'SET_TICKETS_REQUEST';
export {
    PURCHASE_TICKET,
    GET_TICKETS,
    GET_TICKETS_REQUEST,
    SET_TICKETS_REQUEST
}